@startuml
participant Client
participant WebServer
participant WebSocketServer as WS
participant Blokus

activate Client
Client --> WebServer : [GET] index.html
activate WebServer
WebServer --> Client : Response index.html
deactivate WebServer
Client --> WS : [Connect]
activate WS
WS --> Blokus : Create
activate Blokus
WS --> Blokus : Start game
...
Blokus --> WS : start game
WS --> Client : start game
...
WS --> Client : cannot start game
note left
・何らかの原因でゲームを開始できない時に送られる。
（例えばリソース不足であったり、サーバーがサービスを停止していたり。）
・これが送られたらDisconnectを送信するか、待ち状態に入る。
・ゲームを開始できるようになったらstart gameが送られてくる。
（多分使わない）
end note
...
WS --> Client : pause game
note left
・何らかの原因でゲームを一時停止する時に送られる。
・これが送られたら待ち状態に入る。
・再開するときはresume gameが送られてくる。
（多分使わない）
end note
...
WS --> Client : resume game
...
Blokus --> WS : mino placed info
WS --> Client : mino placed info (mino id, owner, row, col, rotate times, flipped)
note left
1.Boardの所定の位置にMinoを追加
2.PlayerもしくはAIの所持しているMinoリストからMinoを削除
end note
...
WS --> Client : time out
note left
・操作が行われずに一定時間が経過すると送られる。
・これが送られると基本的にサーバー側からDisconnectされる。
（多分使わない）
end note
...
Blokus --> WS : Get first place
WS --> Client : Get first place
note left
・Boardの入力ステートを入力可能にする
・流れ（Get try placeも同じ）
1.Get first place
2.Send first place info
・成功
3.Receive Mino placed info (Player)
4.Receive Mino placed info (AI)
continue...
・失敗
3.invalid place location
4.Get first place
end note
Client --> WS : first place info (mino id, row, col, rotate times, flipped)
WS --> Blokus : first place info
...
Blokus --> WS : Get try place
WS --> Client : Get try place
Client --> WS : try place info (mino id, row, col, rotate times, flipped)
WS --> Blokus : try place info
...
Blokus --> WS : invalid place location (message)
WS --> Client : invalid place location (message)
note left
・Get first placeやGet try placeで指定された座標が無効だった場合に送られる。
・AlertとかでMessageを表示させる。
end note
...
Blokus --> WS : Failed (message)
WS --> Client : Failed (message)
note left
・なんらかの技術的な問題でこれ以上ゲームが継続できなくなった時に送られる。
・これが送られるとサーバー側からDisconnectされる。
・その後、AlertなどでMessageを表示させる。
end note
...
Blokus --> WS : Skip
WS --> Client : Skip
note left
盤面の関係でPlayerがSkipせざる終えない時に送られる。
（この場合はPlayerはもう最後まで置ける場所がないがAIはまだ置けるという状況。）
（つまりPlayerにとって"詰み"を意味しておりまた、同時に"負け"を意味している。）
AIが置けない場合は送られず、次のGet try placeが送られる。
end note
...
Client --> WS : [Disconnect]
WS --> Blokus : Destroy
note right
明示的にしっかり殺してやる。
end note
...
Blokus --> WS : finish info
WS --> Client : finish info (winner)
...
WS --> Blokus : Destroy
deactivate Blokus
Client --> WS : [Disconnect]
deactivate WS
deactivate Client
@enduml